# Arquivo: .golangci.yml

linters:
  enable:
    - gocyclo
    - gocognit
    - funlen
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 35
  gocognit:
    min-complexity: 35
  funlen:
    lines: 120
    statements: 60