# Arquivo: .golangci.yml

linters:
  enable:
    - gocyclo
    - gocognit
    - funlen
    - dupl

linters-settings:
  gocyclo:
    # Falha se a complexidade for maior que 15
    min-complexity: 15
  gocognit:
    # Complexidade cognitiva máxima permitida
    min-complexity: 10
  funlen:
    # Máximo de 50 linhas por função
    lines: 50
    statements: 30